Organizations:
  - &Orderer
    Name: Orderer
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/acme.com/msp

  - &Org1
    Name: Org1
    ID: Org1MSP
    MSPDir: ./crypto-config/peerOrganizations/acme.com/msp
    AnchorPeers:
      - Host: localhost
        Port: 7051
Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
      - localhost:7050
    BatchTimeout: 2s
    BatchSize:
      MaxMessageCount: 10
      AbsoluteMaxBytes: 98 MB
      PreferredMaxBytes: 512KB
    MaxChannels: 0
Application: &ApplicationDefaults
      Organizations:

Channel: &ChannelDefaults

Profiles:
  
  AcmeOrdererGenesis:
    Orderer:
      << : *OrdererDefaults
      Organizations:
          - *Orderer
    Consortiums:
      AirlineConsortium:
        Organizations:
            - *Org1
  AcmeChannel:
    Consortium: AirlineConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1